# Generated by Django 5.1.4 on 2025-07-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_first_n_8f83e0_idx'),
    ]

    operations = [
        migrations.RunSQL(
            # Opening statement
            """
            INSERT INTO store_collection (title)
            VALUES ('collection1')    
            """,
            # Closing statement
            """
            DELETE FROM store_collection
            WHERE title='collection1'    
            """
        )
    ]
