# Generated by Django 5.1.4 on 2025-07-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
